# Generated by Django 5.0 on 2024-12-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_own_todo", "Can view own todo")],
                "verbose_name": "待辦事項",
                "verbose_name_plural": "待辦事項",
            },
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="是否完成"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=200, verbose_name="標題"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
    ]
