version: "3.8"

services:
  nginx:
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    environment:
      - NGINX_HOST=dev.bluegajournal.com
      - NGINX_PORT=80

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bluega_journal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    depends_on:
      - db

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://dev.bluegajournal.com/api
    depends_on:
      - backend

volumes:
  postgres_data:
