version: "3.8"

services:
  nginx:
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    environment:
      - NGINX_HOST=dev.bluegajournal.com
      - NGINX_PORT=80

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod # 使用生產環境的 Dockerfile
    volumes:
      - ../../backend:/app # 保留開發時的代碼掛載
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ../../.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    depends_on:
      - db

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod # 使用生產環境的 Dockerfile
    volumes:
      - ../../frontend:/app # 保留開發時的代碼掛載
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://dev.bluegajournal.com/api
    depends_on:
      - backend

volumes:
  postgres_data_dev:
  static_volume:
  media_volume:
