version: "3.8"

# 首先定義網絡
networks:
  dev_network:
    driver: bridge

services:
  nginx:
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    environment:
      - NGINX_HOST=dev.bluegajournal.com

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../../backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - dev_network
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DB_NAME=bluega_journal_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
      - ALLOWED_HOSTS=dev.bluegajournal.com,localhost,3.24.138.130
      - CORS_ALLOWED_ORIGINS=http://dev.bluegajournal.com,http://localhost,http://3.24.138.130
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        sleep 10 &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    networks:
      - dev_network
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://dev.bluegajournal.com/api # 更新 API URL
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network
    environment:
      - POSTGRES_DB=bluega_journal_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
  static_volume:
  media_volume:
