# 構建階段
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# 生產階段
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 80