# Build stage
FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Nginx 階段
FROM nginx:alpine

# 從構建階段複製構建文件
COPY --from=builder /app/dist /usr/share/nginx/html

# 設置權限
RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 80 443
