version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bluegajournal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=bluegajournal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db # 這裡改為 db，而不是 localhost
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOW_ALL_ORIGINS=True
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
             
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
