version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-bluegajournal}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    env_file:
      - .env.prod
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings
      - ALLOWED_HOSTS=3.24.138.130,localhost,127.0.0.1,www.bluegajournal.com,bluegajournal.com
      - DB_NAME=${DB_NAME:-bluegajournal}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env.prod
    expose: # 只在內部網絡暴露端口
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/api/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - build_volume:/app/dist
    networks:
      - app-network
    environment:
      - VITE_API_URL=https://www.bluegajournal.com/api
    restart: "no" # 改變重啟策略
    healthcheck:
      disable: true # 禁用健康檢查
    depends_on:
      - backend
    command: ["echo", "Frontend build completed"] # 添加簡單的命令

    nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      volumes:
        - static_volume:/usr/share/nginx/static:ro
        - media_volume:/usr/share/nginx/media:ro
        - build_volume:/usr/share/nginx/html:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # 添加 nginx.conf
        - ./nginx/cache:/var/cache/nginx # 添加緩存目錄
        - ./certbot/conf:/etc/letsencrypt:ro # 添加證書
        - ./certbot/www:/var/www/certbot:ro # 添加 certbot 驗證目錄
      ports:
        - "80:80"
        - "443:443" # 添加 HTTPS 端口
      depends_on:
        backend:
          condition: service_healthy
        frontend:
          condition: service_completed_successfully
        certbot:
          condition: service_completed_successfully # 等待證書服務
      networks:
        - app-network
      restart: always # 改回 always，確保服務持續運行
      healthcheck:
        test: [
            "CMD-SHELL",
            "curl -f https://localhost/health_check -k || exit 1",
          ] # 修改健康檢查路徑
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 20s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  build_volume: # 用於存儲構建結果
