version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # 使用生產環境 Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${API_URL}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod # 使用生產環境 Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
      - DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_PORT=${RDS_PORT}
