# docker/local/docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bluega_journal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - bluega_network_dev

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - bluega_network_dev

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # 啟用輪詢以改善檔案監控
      - NODE_ENV=development
      - VITE_ENV=local
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - bluega_network_dev

volumes:
  postgres_data:

networks:
  bluega_network_dev:
    name: bluega_network_dev
