version: "3.8"

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
    container_name: bluega_frontend_prod
    volumes:
      - ../../frontend/dist:/app/dist
      - /app/node_modules
    expose:
      - "80"
    networks:
      - bluega_network_prod

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    container_name: bluega_backend_prod
    volumes:
      - ../../backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - POSTGRES_DB=bluega_journal_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=bluega_db_prod
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    networks:
      - bluega_network_prod

  nginx:
    image: nginx:alpine
    container_name: bluega_nginx_prod
    build:
      context: ../../nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../nginx/conf.d/prod:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - bluega_network_prod

  db:
    image: postgres:15-alpine
    container_name: bluega_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bluega_journal_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - bluega_network_prod
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: bluega_redis_prod
    ports:
      - "6379:6379"
    networks:
      - bluega_network_prod

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

networks:
  bluega_network_prod:
    driver: bridge
