version: "3.8"

services:
  nginx:
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443" # 如果使用 SSL
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl # SSL 證書
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    environment:
      - NGINX_HOST=bluegajournal.com
      - NGINX_PORT=80

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ../../.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://bluegajournal.com/api
    depends_on:
      - backend

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
