FROM nginx:alpine

# 不需要刪除默認配置，直接複製新的配置即可
COPY conf.d/prod/default.conf /etc/nginx/conf.d/default.conf

# 創建必要的目錄
RUN mkdir -p /etc/nginx/ssl /var/log/nginx

# 設置權限
RUN chmod -R 755 /etc/nginx/conf.d \
    && chown -R nginx:nginx /var/log/nginx

# 暴露端口
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]