name: Backend CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: bluegajournal
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DEBUG: True
          DJANGO_SECRET_KEY: test-key
          DB_NAME: bluegajournal
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          cd backend
          python manage.py

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linting
        run: |
          cd backend
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  build:
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Static Files
        env:
          DEBUG: False
          DJANGO_SECRET_KEY: build-key
          ALLOWED_HOSTS: localhost,127.0.0.1
          DB_NAME: bluegajournal
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          cd backend
          python manage.py collectstatic --noinput

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t bluegajournal-backend .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag bluegajournal-backend ${{ secrets.DOCKER_HUB_USERNAME }}/bluegajournal-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bluegajournal-backend:latest

      - name: Cache Build Artifacts
        uses: actions/cache@v3
        with:
          path: |
            backend/staticfiles
            backend/dist
          key: ${{ runner.os }}-django-build-${{ github.sha }}
