name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_FRONTEND: digital-planner-frontend
          ECR_REPOSITORY_BACKEND: digital-planner-backend
        run: |
          # Build frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA -f frontend/Dockerfile.prod frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA

          # Build backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA -f backend/Dockerfile.prod backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster digital-planner --service frontend --force-new-deployment
          aws ecs update-service --cluster digital-planner --service backend --force-new-deployment
