name: Deploy to AWS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 清理舊的部署
            cd ~/BluegaJournal || exit
            docker-compose -f docker-compose.prod.yml down || true

            # 更新代碼
            git fetch origin
            git reset --hard origin/master

            # 重建並啟動服務
            docker-compose -f docker-compose.prod.yml up -d --build --force-recreate

            # 等待數據庫就緒
            sleep 30

            # 執行數據庫遷移（帶重試機制）
            for i in {1..5}; do
              docker-compose -f docker-compose.prod.yml exec -T backend python manage.py migrate && break
              echo "Migration attempt $i failed, retrying in 10 seconds..."
              sleep 10
            done

            # 收集靜態文件
            docker-compose -f docker-compose.prod.yml exec -T backend python manage.py collectstatic --noinput
