name: Deploy to Development

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          mkdir -p ~/BluegaJournal
          cd ~/BluegaJournal
          git clone https://github.com/jinny8813/BluegaJournal.git .
          git checkout dev
          chmod +x scripts/deploy-dev.sh
          ./scripts/deploy-dev.sh